[agent]
  interval = "10s"
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://192.168.1.30:1883"]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
  topics = ["homeassistant/statestream/#"]
  data_format = "value"
  data_type = "string"
  name_override = "ha_statestream"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "homeassistant/statestream/+/+/+"
    tags = "_/_/domain/entity/attribute"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "hausmeister"
  bucket = "sensors"
